
name: Build Image on Tag Push

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  create_docker_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Git Tag
        run: |
          echo "Git Tag: ${{ github.ref_name }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image for Multiple Platforms
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t serhiiham/face_analyzer:${{ github.ref_name }} \
            -t serhiiham/face_analyzer:latest \
            --push .

      - name: Debug Images
        run: |
          echo "Images have been pushed to Docker Hub: serhiiham/face_analyzer:${{ github.ref_name }} and serhiiham/face_analyzer:latest"
